---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cahe: yes

- name: Deploy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Ensure Nginx is running
  service:
    name: nginx
    state: state
    enabled: true
